doLittle.namespace("doLittle.validation");
doLittle.Exception.define("doLittle.validation.OptionsNotDefined", "Option was undefined");
doLittle.Exception.define("doLittle.validation.OptionsValueNotSpecified", "Required value in Options is not specified. ");
doLittle.Exception.define("doLittle.validation.NotANumber", "Value is not a number");
doLittle.Exception.define("doLittle.validation.NotAString", "Value is not a string");
doLittle.Exception.define("doLittle.validation.ValueNotSpecified","Value is not specified");
doLittle.Exception.define("doLittle.validation.MinNotSpecified","Min is not specified");
doLittle.Exception.define("doLittle.validation.MaxNotSpecified","Max is not specified");
doLittle.Exception.define("doLittle.validation.MinLengthNotSpecified","Min length is not specified");
doLittle.Exception.define("doLittle.validation.MaxLengthNotSpecified","Max length is not specified");
doLittle.Exception.define("doLittle.validation.MissingExpression","Expression is not specified");